openapi: 3.0.3
info:
  title: cw-auth-api
  description: |
    Authentication microservice
  version: 1.0.0
servers:
- url: /rest/cw-auth-api/v1.0/
paths:
  /allUsers:
    post:
      tags:
      - All Users
      summary: Obtener todos los usuarios
      description: Obtener todos los usuarios
      operationId: all_users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAllUsers'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAllUsers'
        "404":
          description: Not found users yet
      x-openapi-router-controller: swagger_server.controllers.all_users_controller.AllUsersView
  /users/{code_email}:
    delete:
      tags:
      - Delete User
      summary: Eliminar usuario.
      description: Eliminar usuario.
      operationId: delete_user
      parameters:
      - name: code_email
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: code_email
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDeleteUser'
        "404":
          description: User invalid
      x-openapi-router-controller: swagger_server.controllers.delete_user_controller.DeleteUserView
    patch:
      tags:
      - Update User
      summary: Actualizar usuario.
      description: Actualizar usuario.
      operationId: update_user
      parameters:
      - name: code_email
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: code_email
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateUser'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUpdateUser'
        "400":
          description: Bad Request
      x-openapi-router-controller: swagger_server.controllers.update_user_controller.UpdateUserView
  /checkUser:
    post:
      tags:
      - Check user
      summary: Obtener un usuario
      description: Obtener un usuario
      operationId: get_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCheckUser'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCheckUser'
        "404":
          description: User not Found
      x-openapi-router-controller: swagger_server.controllers.check_user_controller.CheckUserView
  /signup:
    post:
      tags:
      - Signup
      summary: Registrar vendedor
      description: Registrar vendedor
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSignup'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSignup'
        "400":
          description: Invalid data
      x-openapi-router-controller: swagger_server.controllers.signup_controller.SignupView
  /registerUserByAdmin:
    post:
      tags:
      - Register user
      summary: Registrar usuario
      description: Registrar usuario desde el administrador
      operationId: register_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRegisterUserByAdmin'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRegisterUserByAdmin'
        "400":
          description: Invalid data
      x-openapi-router-controller: swagger_server.controllers.register_user_controller.RegisterUserView
  /signin:
    post:
      tags:
      - Signin users
      summary: Inicio de sesion de usuarios
      description: Inicio de sesion de usuarios
      operationId: signin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestSignin'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSignin'
        "400":
          description: Invalid credentials
      x-openapi-router-controller: swagger_server.controllers.signin_users_controller.SigninView
  /tokenResetPassword:
    post:
      tags:
      - Token Reset Password
      summary: Generar token para resetear password
      description: Generar token para resetear password
      operationId: token_reset_password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTokenResetPassword'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTokenResetPassword'
        "400":
          description: Invalid code_email
      x-openapi-router-controller: swagger_server.controllers.token_reset_password_controller.TokenResetPasswordView
  /resetPassword:
    post:
      tags:
      - Reset Password
      summary: Resetear password
      description: Resetear password
      operationId: reset_password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestResetPassword'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResetPassword'
        "400":
          description: Invalid token
      x-openapi-router-controller: swagger_server.controllers.reset_password_controller.ResetPasswordView
components:
  schemas:
    RequestAllUsers:
      required:
      - channel
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
    RequestResetPassword:
      required:
      - channel
      - data
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          $ref: '#/components/schemas/ResetPasswordData'
    RequestTokenResetPassword:
      required:
      - channel
      - code_email
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        code_email:
          type: string
          example: admin@xtrim.ec
    RequestSignin:
      required:
      - channel
      - data
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          $ref: '#/components/schemas/SigninData'
    RequestRegisterUserByAdmin:
      required:
      - channel
      - data
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          $ref: '#/components/schemas/UserData'
    RequestSignup:
      required:
      - channel
      - data
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        api_data:
          $ref: '#/components/schemas/ApiData'
        data:
          $ref: '#/components/schemas/SignupData'
    RequestCheckUser:
      required:
      - channel
      - code_email
      - externalTransactionId
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        code_email:
          type: string
          example: admin@xtrim.ec
    RequestUpdateUser:
      properties:
        channel:
          type: string
          example: CHANNEL
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          $ref: '#/components/schemas/UserData'
    ApiData:
      type: object
      properties:
        codVendor:
          type: string
          example: "102101113"
        identificationNumber:
          type: string
          example: "1206569061"
        city:
          type: string
          example: BABAHOYO
        status:
          type: string
          example: ACTIVO
        email:
          type: string
          example: lv3976400@gmail.com
        cellphone:
          type: string
          example: "999465289"
        goals:
          $ref: '#/components/schemas/GoalsData'
        salesChannel:
          type: string
          example: VINCULADO
        leader:
          type: integer
          example: 0
    GoalsData:
      type: object
      properties:
        Internet_volumen:
          type: integer
          example: 10
        Internet_dolar:
          type: number
          example: 249.9
        Television_volumen:
          type: integer
          example: 0
        Television_dolar:
          type: number
        Telefonia_volumen:
          type: integer
          example: 0
        Telefonia_dolar:
          type: number
          example: 0
    ResetPasswordData:
      type: object
      properties:
        code_email:
          type: string
          example: admin@xtrim.ec
        password:
          type: string
          example: Admin$1234
        token:
          type: string
          example: b411825e90b6ead9
    SigninData:
      type: object
      properties:
        code_email:
          type: string
          example: admin@xtrim.ec
        password:
          type: string
          example: Admin1234
    SignupData:
      type: object
      properties:
        code_email:
          type: string
          example: admin@xtrim.ec
        name:
          type: string
          example: Jorge
        last_name:
          type: string
          example: Ameal
        password:
          type: string
          example: Admin1234
    UserData:
      type: object
      properties:
        code_email:
          type: string
          example: j.alcaraz@xtrim.ec
        status:
          type: boolean
          example: true
        role_id:
          type: integer
          example: 1
        name:
          type: string
          example: Jorge
        last_name:
          type: string
          example: Ameal
        city:
          type: string
          example: Quito
        address:
          type: string
          example: Lugano 1255
        email:
          type: string
          example: j.alcaraz@xtrim.ec
        cellphone:
          type: string
          example: "3592211658"
        department:
          type: string
          example: ventas
        identification_number:
          type: string
          example: "11588468"
        entry_date:
          type: string
          example: 2023-08-14
        password:
          type: string
          example: Sditq124$
      example:
        address: Lugano 1255
        identification_number: "11588468"
        city: Quito
        last_name: Ameal
        entry_date: 2023-08-14
        password: Sditq124$
        role_id: 1
        code_email: j.alcaraz@xtrim.ec
        name: Jorge
        cellphone: "3592211658"
        department: ventas
        email: j.alcaraz@xtrim.ec
        status: true
    ResponseDeleteUser:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Usuario eliminado exitosamente.
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Usuario eliminado exitosamente.
    ResponseResetPassword:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Su contraseña fue reestablecida exitosamente.
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Su contraseña fue reestablecida exitosamente.
    ResponseTokenResetPassword:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: El token para el reset de contraseña fue enviado a su mail.
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: El token para el reset de contraseña fue enviado a su mail.
    ResponseSignin:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Inicio de sesión exitoso
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Inicio de sesión exitoso
    ResponseAllUsers:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Datos obtenidos exitosamente
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Datos obtenidos exitosamente
    ResponseCheckUser:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Datos obtenidos exitosamente
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Datos obtenidos exitosamente
    ResponseUpdateUser:
      properties:
        code:
          type: string
          example: "200"
        message:
          type: string
          example: Usuario actualizado exitosamente.
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          $ref: '#/components/schemas/UserData'
      example:
        code: "200"
        data:
          address: Lugano 1255
          identification_number: "11588468"
          city: Quito
          last_name: Ameal
          entry_date: 2023-08-14
          password: Sditq124$
          role_id: 1
          code_email: j.alcaraz@xtrim.ec
          name: Jorge
          cellphone: "3592211658"
          department: ventas
          email: j.alcaraz@xtrim.ec
          status: true
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Usuario actualizado exitosamente.
    ResponseSignup:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Usuario registrado exitosamente
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Usuario registrado exitosamente
    ResponseRegisterUserByAdmin:
      properties:
        code:
          type: string
          example: "0"
        message:
          type: string
          example: Usuario registrado exitosamente
        internalTransactionId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId:
          type: string
          example: fcea920f7412b5da7be0cf42b8c93759
        data:
          type: object
      example:
        code: "0"
        data: {}
        internalTransactionId: d290f1ee-6c54-4b01-90e6-d701748f0851
        externalTransactionId: fcea920f7412b5da7be0cf42b8c93759
        message: Usuario registrado exitosamente

